### ISSUE TITLE
Load remote images CORS

### ISSUE THREAD

**Issue by dkruchok** [1904labs/dom-to-image-more#14] opened 2019-08-30 07:33 UTC
HI, 
I have an issue with Angular 8+

`Access to XMLHttpRequest at 'http://example.com/images/example_image.png' from origin 'http://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Is there a way to add a header to requests maybe?
Or what can I do with that?

### Browsers

- [ ] Chrome 49+  
- [ ] Firefox 45+

**Comment by mask2012** [comment] 2020-10-16 10:25
I have the same problem, and what even funny is, the same url, my computer always works fine, and other's always CORS.
And one have any clue with this?

**Comment by mask2012** [comment] 2020-10-16 10:26
the first pic is the wrong one, and the second is on my computer, which is always fine.
![image](https://user-images.githubusercontent.com/6481461/96247639-f73b1c00-0fdc-11eb-8c0e-cc87a3e3b285.png)
![image](https://user-images.githubusercontent.com/6481461/96247653-fdc99380-0fdc-11eb-8e0d-cbc5a2d805dc.png)

**Comment by arnonrdp** [comment] 2022-01-09 23:26
I am facing the exactly same problem right now.
@mask2012 @dkruchok did you solved this, guys?

**Comment by tarcisioaraujo** [comment] 2022-12-19 17:27
I have the same problem, has anyone found a solution? Should I implement a proxy server and put requests through it?

**Comment by udayraj713** [comment] 2023-02-07 00:25
Try cacheBust: true

domtoimage.toPng(nodeName, { cacheBust: true })

**Comment by tarcisioaraujo** [comment] 2023-02-07 19:54
> Try cacheBust: true
> 
> domtoimage.toPng(nodeName, { cacheBust: true })

Don't work in all cases

**Comment by emrecoban** [comment] 2023-04-14 12:28
This is a significant issue. There is no need to access the data source within the DOM again. However, you can resolve this issue by using a third-party URL or by setting up your own API server.

### Solution
While there is no guaranteed solution, the problem can be resolved by using [allOrigins](https://allorigins.win/). With [allOrigins](https://allorigins.win/), you can **bypass CORS policies** and access the base64 version of the image, allowing the image in the DOM tree to be displayed.

Using [allOrigins](https://allorigins.win/) is simple (fetch or axios doesn't matter):
`const base64 = await axios.get(https://api.allorigins.win/get?url=${yourImageURL})`

[**Sample Repository**](https://github.com/emrecoban/eksiShot)

**Comment by IDisposable** [comment] 2023-04-14 21:55
That's a really interesting solution, might be able to add an option to pipe all image requests through that automatically (opt-in). Will look into that idea after I do my taxes :)

**Comment by emrecoban** [comment] 2023-04-15 00:51
> That's a really interesting solution, might be able to add an option to pipe all image requests through that automatically (opt-in). Will look into that idea after I do my taxes :)

Actually considered the same solution until I noticed the delay caused by image loading :) Therefore, using a third-party URL and rendering all images may not be efficient. In fact, frameworks with [server-side functions](https://nextjs.org/docs/basic-features/data-fetching/get-server-side-props) like Next.js make it quite easy and eliminate the need for this.

It seems like many people are encountering the same issue. With your permission, I would like to add a comment about this topic in [the readme file](https://github.com/1904labs/dom-to-image-more#readme).

**Closed** 2023-04-16 20:37 UTC
